name = "rip"
main = "src/index.js"
compatibility_date = "2026-04-26"
compatibility_flags = ["nodejs_compat"]

# 自定义域名
# routes = [
#   { pattern = "rip.lgbt/*", zone_name = "rip.lgbt" }
# ]

[vars]
SITE_TITLE = "勿忘我"
SITE_SUBTITLE = "rip.lgbt"
