name = "rip"
main = "src/index.js"
compatibility_date = "2026-04-26"
compatibility_flags = ["nodejs_compat"]

# 自定义域名
# routes = [
#   { pattern = "rip.lgbt/*", zone_name = "rip.lgbt" }
# ]

[vars]
SITE_TITLE = "勿忘我"
SITE_SUBTITLE = "rip.lgbt"

[[durable_objects.bindings]]
name = "ENGAGEMENT"
class_name = "MemorialEngagement"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MemorialEngagement"]
